#!/bin/sh

WINDOW_MANAGER='i3'

# Merge default resources and key maps
userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -r $sysresources ];        then xrdb -merge $sysresources;     fi
if [ -r $sysmodmap ];           then xmodmap $sysmodmap;            fi

if [ -r "$userresources" ];     then xrdb -merge "$userresources";  fi
if [ -r "$usermodmap" ];        then xmodmap "$usermodmap";         fi

# Load system initialization files
find /etc/X11/xinit/xinitrc.d -name '*.sh' -type f -executable 2>/dev/null \
    | sort | while read init; do . "$init"; done; unset init

# Load workstation-specific settings
if [ -r /etc/xprofile ];        then . /etc/xprofile;               fi
if [ -r "$HOME/.xprofile" ];    then . "$HOME/.xprofile";           fi

# Set up specific background applications

# => IBus input method
if which ibus-daemon >/dev/null 2>&1; then
    export XMODIFIERS=@im=ibus GTK_IM_MODULE=ibus QT_IM_MODULE=ibus
    ibus-daemon -drx
fi

# => GPG/SSH agent
unset SSH_AGENT_PID
if [ "${gnupg_SSH_AUTH_SOCK_by:-0}" -ne $$ ]; then
    export SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
fi

# Launch window manager
exec $WINDOW_MANAGER
